name: ubenwa
description: Ubenwa health coding challenge


publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get_it: ^7.6.0
  iconsax: ^0.0.8
  
  

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  test:
  


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logoios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff00"
  

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        
        

